name: Run Python Project and Update JSON Files

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发
  workflow_dispatch:  # 手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. 运行主程序
      - name: Run the Python Script
        run: python x.py

      # 5. 提交更新的 JSON 文件
      - name: Commit and push updated JSON
        run: |
          git config user.name "yzwbeast"
          git config user.email "yzw.beast@gmail.com"
          git add json/*.json
          git commit -m "Update JSON files [skip ci]"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
